pipeline:
  tests:
    image: python:3.9
    environment:
      - DB_CACHE=/tmp
      - DB_NAME=trytontest
      - TRYTOND_DATABASE_URI=postgresql://tryton:tryton@postgres:5432/
    commands:
      - pip3 install psycopg2 proteus
      - python3 setup.py install
      - python3 -m unittest
  notify:
    image: plugins/matrix
    failure: ignore
    settings:
      home_server: https://matrix.org
      roomid: "!oxZmsJwfvciTuLYIwg:matrix.org"
      username:
        from_secret: matrix_user
      password:
        from_secret: matrix_password
    template: >
      PikPukPak..
      <p>${CI_COMMIT_AUTHOR}: <a href="${CI_COMMIT_URL}">${CI_REPO}/${CI_COMMIT_BRANCH}</a><b>${CI_PIPELINE_STATUS}</b></p>
      <pre>${CI_COMMIT_MESSAGE}</pre>
    when:
      - status: [ success, failure ]

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=tryton
      - POSTGRES_PASSWORD=tryton
      - POSTGRES_DB=demo
