pipeline:
  tests:
    image: python:3.9
    environment:
      - DB_CACHE=/tmp
      - DB_NAME=trytontest
      - TRYTOND_DATABASE_URI=postgresql://tryton:tryton@postgres:5432/
    commands:
      - pip3 install psycopg2 proteus
      - python3 setup.py install
      - python3 -m unittest

  notify-success:
    image: plugins/matrix
    settings:
      home_server: https://matrix.org
      roomid: "!oxZmsJwfvciTuLYIwg:matrix.org"
      username:
        from_secret: matrix_user
      password:
        from_secret: matrix_password
    template: >
      PikPukPak..
      <p>${CI_COMMIT_AUTHOR}: JOB ${CI_BUILD_NUMBER} <b style="color: green">TODO BIEN PARA</b></p>
      <pre><a href="${CI_COMMIT_LINK}">${CI_COMMIT_MESSAGE}</a></pre>
    when:
      status: [ success ]

  notify-failure:
    image: plugins/matrix
    settings:
      home_server: https://matrix.org
      roomid: "!oxZmsJwfvciTuLYIwg:matrix.org"
      username:
        from_secret: matrix_user
      password:
        from_secret: matrix_password
    template: >
      PikPukPak..
      <p>${CI_COMMIT_AUTHOR}: JOB ${CI_BUILD_NUMBER} <b style="color: red">!!!TODO MAL PARA</b></p>
      <pre><a href="${CI_COMMIT_LINK}">${CI_COMMIT_MESSAGE}</a></pre>
    when:
      status: [ failure ]

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=tryton
      - POSTGRES_PASSWORD=tryton
      - POSTGRES_DB=demo
