version: '3.9'
include:
  - compose.base.yml
services:
  app.dev:
    image: python:3.9
    depends_on:
      - db.dev
    command: bash .dev/run.sh
    environment:
      - DB_NAME=tryton
      - SRC=/app
      - TRYTOND_DATABASE_URI=postgresql://tryton:tryton@db.dev:5432/
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
