version: '3.9'
include:
  - compose.base.yml
services:
  app.dev:
    build:
      context: .
    environment:
      - SRC=/app
      - DB_CACHE=/tmp
      - DB_NAME=trytontest
      - TRYTOND_DATABASE_URI=postgresql://tryton:tryton@db.dev:5432/
    depends_on:
      - db.dev
    command: sleep 10h
    volumes:
      - .:/app
    working_dir: /app
